backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "_projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Ścieżka", name: "projectSlug", widget: "string"}
      - {label: "Nazwa projektu", name: "projectTitle", widget: "string"}
      - {label: "Typ projektu", name: "projectType", widget: "boolean"}
      - {label: "Okładka", name: "projectCover", widget: "image"}
      - {label: "Zdjęcia projektu", name: "projectPhotos", widget: "image", allow_multiple: true, media_library: { config: { multiple: true }}}
      - {label: "Opis", name: "projectDescription", widget: "markdown"}
      - {label: "Autor", name: "projectDuthor", widget: "string"}
      - {label: "Lokalizacja", name: "projectLocation", widget: "string"}

