backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "architecture" # Used in routes, e.g., /admin/collections/blog
    label: "Architektura" # Used in the UI
    folder: "_posts/architecture_projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "architecture"}
      - {label: "Nazwa projektu", name: "title", widget: "string"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Lokalizacja", name: "location", widget: "string"}
      - {label: "Okładka", name: "cover", widget: "image"}
      - {label: "Opis", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Zdjęcia projektu"
            name: "photos"
            widget: "image"
            allow_multiple: true
            media_library:
              config:
                multiple: true
